# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/139/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/139/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/arkady/C++/CRM-system

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/arkady/C++/CRM-system

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/139/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/139/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arkady/C++/CRM-system/CMakeFiles /home/arkady/C++/CRM-system/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/arkady/C++/CRM-system/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named CRM_system

# Build rule for target.
CRM_system: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CRM_system
.PHONY : CRM_system

# fast build rule for target.
CRM_system/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/build
.PHONY : CRM_system/fast

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/people.o: src/people.cpp.o

.PHONY : src/people.o

# target to build an object file
src/people.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/people.cpp.o
.PHONY : src/people.cpp.o

src/people.i: src/people.cpp.i

.PHONY : src/people.i

# target to preprocess a source file
src/people.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/people.cpp.i
.PHONY : src/people.cpp.i

src/people.s: src/people.cpp.s

.PHONY : src/people.s

# target to generate assembly for a file
src/people.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/people.cpp.s
.PHONY : src/people.cpp.s

src/peopleMVP.o: src/peopleMVP.cpp.o

.PHONY : src/peopleMVP.o

# target to build an object file
src/peopleMVP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/peopleMVP.cpp.o
.PHONY : src/peopleMVP.cpp.o

src/peopleMVP.i: src/peopleMVP.cpp.i

.PHONY : src/peopleMVP.i

# target to preprocess a source file
src/peopleMVP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/peopleMVP.cpp.i
.PHONY : src/peopleMVP.cpp.i

src/peopleMVP.s: src/peopleMVP.cpp.s

.PHONY : src/peopleMVP.s

# target to generate assembly for a file
src/peopleMVP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/CRM_system.dir/build.make CMakeFiles/CRM_system.dir/src/peopleMVP.cpp.s
.PHONY : src/peopleMVP.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CRM_system"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/people.o"
	@echo "... src/people.i"
	@echo "... src/people.s"
	@echo "... src/peopleMVP.o"
	@echo "... src/peopleMVP.i"
	@echo "... src/peopleMVP.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

